apiVersion: apps/v1
kind: Deployment
metadata:
  name: gembook-svc-deployment
  namespace: dev
  labels:
    app: gembook-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gembook-svc
  template:
    metadata:
      labels:
        app: gembook-svc
    spec:
      containers:
      - name: gembook-svc
        image: 947681381905.dkr.ecr.ap-south-1.amazonaws.com/gembook-svc:latest
        ports:
        - name: gembook
          containerPort: 7000
        imagePullPolicy: Always
